### ISSUE TITLE
What is time variable here?

### ISSUE THREAD

**Issue by manvirvirk** [odobenuskr/Deep-EEG#1]

**Comment by james-sungjae-lee** [comment]
Hi, @manvirvirk 

In my preprocessed dataset, "eeg_train_dataset.csv", the column name of "Time-Series" is time variable.
"Time-Series" column has 0 to 255 values because the original dataset is 255Hz of brain signal
You can check the original dataset here - https://archive.ics.uci.edu/ml/datasets/EEG+Database

If you have any other questions, please let me know.
Thank you.
